import { getAuthUserId } from "@convex-dev/auth/server";
import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

const importanceValidator = v.union(v.literal("normal"),v.literal("a_rendre"),v.literal("note"),v.literal("interro"),v.literal("controle"),v.literal("oral"));
export const list = query({args:{},handler:async(ctx)=>{const viewerId=await getAuthUserId(ctx);if(viewerId===null)return[];const viewer=await ctx.db.get(viewerId);const className=viewer?.className;if(!className)return[];const todayStr=new Date().toISOString().slice(0,10);const rows=(await ctx.db.query("homework").withIndex("by_due_date",q=>q.gte("dueDate",todayStr)).collect()).filter(h=>h.className===className);const rank=(h:any)=>h.importance==="controle"?5:h.importance==="interro"?4:h.importance==="note"?3:h.importance==="oral"?3:h.importance==="a_rendre"?2:h.isTest?4:1;rows.sort((a,b)=>a.dueDate===b.dueDate?rank(b)-rank(a):a.dueDate<b.dueDate?-1:1);return rows.map(h=>({_id:h._id,subjectKey:h.subjectKey,dueDate:h.dueDate,text:h.text,emoji:h.emoji,done:h.doneBy.some(id=>id===viewerId),doneCount:h.doneBy.length,mine:h.createdBy===viewerId,source:(h.source??"manuel") as "ecoledirecte"|"manuel",subjectLabel:h.subjectLabel,teacher:h.teacher,isTest:h.isTest,importance:h.importance??(h.isTest?"interro":"normal"),edDone:h.edDone}));}});
export const add=mutation({args:{subjectKey:v.string(),dueDate:v.string(),text:v.string(),emoji:v.string(),importance:v.optional(importanceValidator)},handler:async(ctx,args)=>{const userId=await getAuthUserId(ctx);if(userId===null)throw new Error("Connecte-toi pour ajouter un devoir.");if(!/^\d{4}-\d{2}-\d{2}$/.test(args.dueDate))throw new Error("Date d'échéance invalide.");const text=args.text.trim().slice(0,900);if(!text)throw new Error("Écris d'abord le devoir.");const author=await ctx.db.get(userId);return ctx.db.insert("homework",{subjectKey:args.subjectKey,dueDate:args.dueDate,text,emoji:args.emoji.slice(0,8)||"📝",className:author?.className,doneBy:[],createdBy:userId,createdAt:Date.now(),source:"manuel",importance:args.importance??"normal",isTest:["note","interro","controle","oral"].includes(args.importance??"")});}});
export const toggleDone=mutation({args:{id:v.id("homework")},handler:async(ctx,{id})=>{const userId=await getAuthUserId(ctx);if(userId===null)throw new Error("Connecte-toi d'abord.");const h=await ctx.db.get(id);if(!h)throw new Error("Ce devoir n'existe plus.");const done=h.doneBy.some(uid=>uid===userId);await ctx.db.patch(id,{doneBy:done?h.doneBy.filter(uid=>uid!==userId):[...h.doneBy,userId]});}});
export const remove=mutation({args:{id:v.id("homework")},handler:async(ctx,{id})=>{const userId=await getAuthUserId(ctx);if(userId===null)throw new Error("Connecte-toi d'abord.");const h=await ctx.db.get(id);if(!h)return;if(h.source==="ecoledirecte")throw new Error("Ce devoir vient d'EcoleDirecte — il se met à jour tout seul.");if(h.createdBy!==userId)throw new Error("Tu ne peux supprimer que les devoirs que tu as ajoutés.");await ctx.db.delete(id);}});
